image: python:3.7

before_script:
    - conda create -n mltools python=3.6
    - source activate mltools
    - pip install git+https://github.com/p2327/mltools


stages:
    - test

test:
    stage: test
    script:
        - pytest test_mltools.py
